name: Publish release

on:
  push:
    tags:
    - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sm-version: [ '1.10.x', '1.11.x' ]

    name: SM version ${{ matrix.sm-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup SourcePawn Compiler
      id: setup
      uses: rumblefrog/setup-sp@v1.0.0
      with: 
          version: ${{ matrix.sm-version }}

    - name: Create plugins directory
      run: mkdir -p plugins

    - run: spcomp -i ./scripting/includes ./scripting/deathmatch_loader.sp -o ./plugins/deathmatch_loader.smx

    - name: Prepare files for artifact
      run: |
        mkdir artifact
        mv ./plugins ./artifact/
        mv ./scripting ./artifact/
        mv ./LICENSE ./artifact/

    - name: Zip plugin
      run : |
        cd artifact
        zip -r deathmatch_loader *
        cd ..
        mv artifact/deathmatch-loader-sm${{ steps.setup.outputs.version }}.zip .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }} compiled with SM ${{ steps.setup.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release files
      id: upload-release-files 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deathmatch-loader-sm${{ matrix.sm-version }}.zip.zip
        asset_name: deathmatch-loader-sm${{ matrix.sm-version }}.zip.zip
        asset_content_type: application/zip