name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@v1.0.0
      with: 
          version: 1.10.x

    - run: spcomp -i scripting/includes scripting/deathmatch_loader.sp -o plugins/deathmatch_loader.smx

    - name: Upload compiled plugin
      uses: actions/upload-artifact@v1
      with:
        name: Compiled plugin
        path: plugins/deathmatch_loader.smx
